### ISSUE TITLE
iDevAffiliate Commission Tracking

### ISSUE THREAD

**Issue by jaswsinc** [websharks/s2member-kb#128]
---
##### KB Article Creation Checklist

- [x] Write initial draft for this KB Article; label this issue `draft` and either `questions` or `tutorials`
- [x] Add [required YAML configuration](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration)
- [x] Add Tags for this KB Article to the YAML config (see [YAML Keys (Explained)](https://github.com/websharks/team/wiki/KB-Articles-::-Required-YAML-Configuration#yaml-keys-explained))
- [x] Edit and finalize draft for publishing (remove `draft` label, add `draft-finalized` label)
- [x] Assign Issue to yourself and [create Markdown file](https://github.com/websharks/team/wiki/KB-Articles-::-Creating-the-Markdown-File) (remove `draft-finalized` label, add `pending`)
- [x] Project Lead: Review and Publish KB Article (remove `pending` label, add `published` label)

##### Additional TODOs

_Additional TODO list items go here._

---

**Markdown File:** http://wsharks.com/1Fzkips
**Published KB Article:** http://s2member.com/kb-article/idevaffiliate-commission-tracking/

---

**Comment by patdumond** [comment]
Reference Zendesk ticket: https://websharks.zendesk.com/agent/tickets/6472.

This isn't exactly about the integration of iDev Affiliates and s2Member, but the user found that under ‘Fraud Controls’ in iDev - the ‘time delay’ to stop duplicate commissions was somehow set to 360 hours. This kept s2Member and iDev from "linking up" on checking recurring subscriptions. If the user wants to check daily, that value has to be less than 24.

**Comment by jhall3rd** [comment]
Very confusing post. It contradicts the idev integration instructions which very clearly state that the correct url format for payment notification is this:
https://domain/idevaffiliate/sale.php?profile=83&idev_saleamt=%%amount%%&idev_ordernum=%%txn_id%%&coupon_code=%%coupon_code%%&ip_address=%%user_ip%%

Also in the image here you show the affiliate id snippet -- should that be used in addition to the ip address -- or instead of?? This entire post raises so many questions and is made worse by the fact that the video has ben removed from youtube. 

We've ben trying to get idev to track recurring comms to no avail -- and I can't tell you how hard this is when idev & s2m present conflicting instructions. Any guidance appreciated.

**Comment by jhall3rd** [comment]
Also in question here are all of the other notifications listed here as part of the advanced method -- cancel, refund, modification -- these are very important parts of the integration. Should we be following these instructions?

**Comment by TOTLD** [comment]
Hi guys,

As per comments above, I'm finding the s2M documentation is telling me different things than the iDev documentation. 

It also seems to be for an out-dated version of iDevAffiliate, since none of the screenshots look anything like the admin dashboard does any more. That includes some stuff not even being in the same menu locations any more. 

Is this still the best choice?

**Comment by jhall3rd** [comment]
the docs re idev/s2m are now out of date. 

it’s not too hard to figure out how to use idev with s2m but i would avoid this combo for recurring comm tracking.

**Comment by TOTLD** [comment]
@jhall3rd - I've been working through it and while I'm not yet testing anything it seems like it _should_ work for recurring commissions..?

Is there any reason you 'would avoid' it specifically? And/or have you got any other suggestions? I still find comfort that iDev is the reference point in the s2M documentation, even if it is out-dated.

**Comment by jhall3rd** [comment]
we could never get recurring comms to register with idev. We tried for many months and eventually had to write custom code to recognize and record recurrings. I spend thousands of dollars on this. Do a test yourself! Just create a recurring of say 1 week and see what happens (1 week is the shortest interval the system can handle).

**Comment by TOTLD** [comment]
@jhall3rd - I'm in a lucky position that my client isn't necessarily looking for ongoing commissions, though I would have liked the option since it is clearly advertised as the major benefit to setting up iDev the 'advanced' way. 

@jaswrks any input from s2Member on that? I understand times change and compatibilities do too, but all the documentation is leading me to spend money expecting a particular outcome...
